### ISSUE TITLE
Add github link to package.json of packages

### ISSUE THREAD

**Issue by TimoGlastra** [transmute-industries/vc.js#43]
This is a minor nitpick but would make it a lot easier to go from npm to github (and from github to github).

Two reasons:
1. When on NPM you can't go directly to Github (it renders a link if present in package.json). You have to manually find where the package is located. With monorepos this can be inconvient.
2. I'm using OctoLinker which adds links to file/package imports in the Github Web UI. If you have a link to the Github repo in your package.json it will automatically link them together.

E.g. for the `@transmute/vc.js` package this will mean adding the following to the package.json:

```jsonc
{
  "name": "@transmute/vc.js",
  // ...
  "repository": {
    "type" : "git",
    "url" : "https://github.com/transmute-industries/vc.js.git",
    "directory": "packages/vc.js"
  },
  "homepage": "https://github.com/transmute-industries/vc.js/tree/master/packages/vc.js",
  // OR 
  "homepage": "https://transmute-industries.github.io/vc.js/"
}
```

Happy to assist if you agree :)

**Comment by OR13** [comment]
@TimoGlastra thanks yes, I noticed this.... I would welcome such a PR. Thanks for raising the issue.

**Comment by TimoGlastra** [comment]
Cool, I've opened #44
